name: Build

on:
    push:
        branches: [master]
    pull_request:
    release:
        types: [created]
    schedule:
        -   cron: '0 4 * * *'

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Build and test
        strategy:
            matrix:
                php: [7.2, 7.3, 7.4, 8.0]
                deps: [high]
                include:
                    -   php: 7.2
                        deps: low

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    tools: flex
                    ini-values: "phar.readonly=0"

            -   if: matrix.deps == 'high'
                run: make install test package package-devkit

            -   if: matrix.deps == 'low'
                run: make update-min test-min

            -   uses: actions/upload-artifact@v1
                if: matrix.php == '7.2' && matrix.deps == 'high'
                with:
                    name: toolbox.phar
                    path: build/toolbox.phar

            -   uses: actions/upload-artifact@v1
                if: matrix.php == '7.2' && matrix.deps == 'high'
                with:
                    name: devkit.phar
                    path: build/devkit.phar

    integration-tests:
        runs-on: ubuntu-latest
        name: Run integration tests
        needs: tests
        strategy:
            matrix:
                php: [7.2, 7.3, 7.4, 8.0]

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    tools: flex
                    ini-values: "phar.readonly=0"

            -   uses: actions/download-artifact@v1
                with:
                    name: toolbox.phar
                    path: build/

            -   run: make test-integration

    publish-phars:
        runs-on: ubuntu-latest
        name: Publish PHARs
        needs: tests
        if: github.event_name == 'release'
        steps:
            -   uses: actions/download-artifact@v1
                with:
                    name: toolbox.phar
                    path: .
            -   uses: actions/download-artifact@v1
                with:
                    name: devkit.phar
                    path: .
            -   name: Upload toolbox.phar
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: ./toolbox.phar
                    asset_name: toolbox.phar
                    asset_content_type: application/zip
            -   name: Upload devkit.phar
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: ./devkit.phar
                    asset_name: devkit.phar
                    asset_content_type: application/zip
